export type DriverMobileLanguage = "en" | "pt" | "lv" | "ru";

export const DRIVER_MOBILE_LANGUAGES: Array<{ value: DriverMobileLanguage; label: string }> = [
  { value: "en", label: "English" },
  { value: "pt", label: "Português" },
  { value: "lv", label: "Latviešu" },
  { value: "ru", label: "Русский" },
];

export const DRIVER_MOBILE_LANGUAGE_KEY_PREFIX = "ferryspeed.driver-mobile.language.";

type DriverMobileTranslationKey =
  | "driverMobile" | "myJobs" | "signOut" | "toDo" | "inProgress" | "completedToday"
  | "needsAttention" | "new" | "overdue" | "offlineAction" | "operationalInstructions"
  | "unread" | "loadingInstructions" | "noStandaloneInstructions" | "instructionOnly"
  | "sent" | "acknowledged" | "acknowledgePending" | "acknowledgeThisJob"
  | "respondToOperations" | "addNote" | "optionalNote" | "cancel" | "responseSent"
  | "schedule" | "reference" | "acknowledgedLabel" | "completed" | "collection"
  | "delivery" | "temperatureRequired" | "collectionReading" | "notes" | "retry"
  | "noJobs" | "offline" | "savedWaitingConnection" | "sending" | "failedRetry"
  | "newInstruction" | "newMessage" | "newAssignment" | "attention" | "critical"
  | "normal" | "ok" | "arrived" | "delayed" | "problem" | "callMe"
  | "collected" | "delivered" | "driverProfileRequired" | "connectionProblem"
  | "unableToLoadJobs" | "unableToLoadInstructions" | "unableToAcknowledge"
  | "unableToSendResponse" | "temperatureReadingRequired" | "temperatureValidNumber";

type TranslationTable = Record<DriverMobileTranslationKey, string>;

const english: TranslationTable = {
  driverMobile: "Ferryspeed Driver Mobile", myJobs: "My Jobs", signOut: "Sign out", toDo: "To Do", inProgress: "In Progress", completedToday: "Completed Today",
  needsAttention: "Needs Attention", new: "NEW", overdue: "OVERDUE", offlineAction: "OFFLINE ACTION", operationalInstructions: "Operational Instructions", unread: "unread", loadingInstructions: "Loading instructions...", noStandaloneInstructions: "No standalone instructions right now.", instructionOnly: "Instruction Only", sent: "Sent", acknowledged: "Acknowledged", acknowledgePending: "Acknowledge pending", acknowledgeThisJob: "Acknowledge this job to confirm the instruction.", respondToOperations: "Respond to Operations", addNote: "Add note", optionalNote: "Optional note", cancel: "Cancel", responseSent: "Response sent", schedule: "Schedule", reference: "Reference", acknowledgedLabel: "Acknowledged", completed: "Completed", collection: "Collection", delivery: "Delivery", temperatureRequired: "Temperature required", collectionReading: "Collection reading (C)", notes: "Notes", retry: "Retry", noJobs: "No jobs in this section.", offline: "Offline. Saved actions will send when connection returns.", savedWaitingConnection: "Saved - waiting for connection", sending: "Sending...", failedRetry: "Could not finish. Retry", newInstruction: "NEW INSTRUCTION", newMessage: "NEW MESSAGE", newAssignment: "NEW ASSIGNMENT", attention: "ATTENTION", critical: "CRITICAL", normal: "Normal", ok: "OK", arrived: "ARRIVED", delayed: "DELAYED", problem: "PROBLEM", callMe: "CALL ME", collected: "RECOLHIDA / COLLECTED", delivered: "ENTREGUE / DELIVERED", driverProfileRequired: "Driver profile required", connectionProblem: "Connection problem", unableToLoadJobs: "Unable to load assigned jobs.", unableToLoadInstructions: "Unable to load operational instructions.", unableToAcknowledge: "Unable to acknowledge instruction.", unableToSendResponse: "Unable to send instruction response.", temperatureReadingRequired: "Temperature reading is required before marking as collected.", temperatureValidNumber: "Temperature must be a valid number.",
};

const portuguese: TranslationTable = { ...english, driverMobile: "Ferryspeed Mobile do Motorista", myJobs: "Os meus serviços", signOut: "Sair", toDo: "A fazer", inProgress: "Em curso", completedToday: "Concluídos hoje", needsAttention: "Requer atenção", new: "NOVO", overdue: "EM ATRASO", offlineAction: "AÇÃO OFFLINE", operationalInstructions: "Instruções operacionais", unread: "por ler", loadingInstructions: "A carregar instruções...", noStandaloneInstructions: "Não há instruções independentes.", instructionOnly: "Apenas instrução", sent: "Enviado", acknowledged: "Confirmado", acknowledgePending: "Confirmação pendente", acknowledgeThisJob: "Confirme este serviço para validar a instrução.", respondToOperations: "Responder às operações", addNote: "Adicionar nota", optionalNote: "Nota opcional", cancel: "Cancelar", responseSent: "Resposta enviada", schedule: "Horário", reference: "Referência", acknowledgedLabel: "Confirmado", completed: "Concluído", collection: "Recolha", delivery: "Entrega", temperatureRequired: "Temperatura obrigatória", collectionReading: "Leitura de recolha (C)", retry: "Tentar novamente", noJobs: "Não há serviços nesta secção.", offline: "Sem ligação. As ações guardadas serão enviadas quando a ligação voltar.", sending: "A enviar...", failedRetry: "Não foi possível concluir. Tentar novamente", attention: "ATENÇÃO", critical: "CRÍTICO", normal: "Normal", arrived: "CHEGUEI", delayed: "ATRASADO", problem: "PROBLEMA", callMe: "LIGUE-ME", collected: "Recolhido", delivered: "Entregue", driverProfileRequired: "Perfil de motorista necessário", unableToLoadJobs: "Não foi possível carregar os serviços.", unableToLoadInstructions: "Não foi possível carregar as instruções.", unableToAcknowledge: "Não foi possível confirmar a instrução.", unableToSendResponse: "Não foi possível enviar a resposta.", temperatureReadingRequired: "É necessária uma leitura de temperatura antes de marcar como recolhido.", temperatureValidNumber: "A temperatura deve ser um número válido.", };
const latvian: TranslationTable = { ...english, driverMobile: "Ferryspeed vadītāja mobilā lietotne", myJobs: "Mani darbi", signOut: "Izrakstīties", toDo: "Veicamie", inProgress: "Procesā", completedToday: "Šodien pabeigti", needsAttention: "Nepieciešama uzmanība", new: "JAUNS", overdue: "KAVĒTS", offlineAction: "DARBĪBA BEZSAISTĒ", operationalInstructions: "Operatīvie norādījumi", unread: "nelasīti", loadingInstructions: "Ielādē norādījumus...", noStandaloneInstructions: "Nav atsevišķu norādījumu.", instructionOnly: "Tikai norādījums", sent: "Nosūtīts", acknowledged: "Apstiprināts", acknowledgePending: "Apstiprināšana gaida", acknowledgeThisJob: "Apstipriniet šo darbu, lai apstiprinātu norādījumu.", respondToOperations: "Atbildēt operācijām", addNote: "Pievienot piezīmi", optionalNote: "Piezīme (neobligāta)", cancel: "Atcelt", responseSent: "Atbilde nosūtīta", schedule: "Grafiks", reference: "Atsauce", acknowledgedLabel: "Apstiprināts", completed: "Pabeigts", collection: "Paņemšana", delivery: "Piegāde", temperatureRequired: "Nepieciešama temperatūra", collectionReading: "Paņemšanas rādījums (C)", retry: "Mēģināt vēlreiz", noJobs: "Šajā sadaļā nav darbu.", offline: "Bezsaistē. Saglabātās darbības tiks nosūtītas, kad savienojums atjaunosies.", sending: "Sūta...", failedRetry: "Neizdevās pabeigt. Mēģināt vēlreiz", attention: "UZMANĪBU", critical: "KRITISKS", normal: "Parasts", arrived: "IERADOS", delayed: "KAVĒJOS", problem: "PROBLĒMA", callMe: "PIEZVANIET MAN", collected: "Paņemts", delivered: "Piegādāts", driverProfileRequired: "Nepieciešams vadītāja profils", unableToLoadJobs: "Nevar ielādēt darbus.", unableToLoadInstructions: "Nevar ielādēt norādījumus.", unableToAcknowledge: "Nevar apstiprināt norādījumu.", unableToSendResponse: "Nevar nosūtīt atbildi.", temperatureReadingRequired: "Pirms atzīmēšanas par paņemtu nepieciešams temperatūras rādījums.", temperatureValidNumber: "Temperatūrai jābūt derīgam skaitlim.", };
const russian: TranslationTable = { ...english, driverMobile: "Ferryspeed Мобильное приложение водителя", myJobs: "Мои задания", signOut: "Выйти", toDo: "К выполнению", inProgress: "В процессе", completedToday: "Выполнено сегодня", needsAttention: "Требует внимания", new: "НОВОЕ", overdue: "ПРОСРОЧЕНО", offlineAction: "ДЕЙСТВИЕ ОФЛАЙН", operationalInstructions: "Операционные инструкции", unread: "непрочитано", loadingInstructions: "Загрузка инструкций...", noStandaloneInstructions: "Нет отдельных инструкций.", instructionOnly: "Только инструкция", sent: "Отправлено", acknowledged: "Подтверждено", acknowledgePending: "Ожидает подтверждения", acknowledgeThisJob: "Подтвердите это задание, чтобы подтвердить инструкцию.", respondToOperations: "Ответить операционной службе", addNote: "Добавить примечание", optionalNote: "Примечание (необязательно)", cancel: "Отмена", responseSent: "Ответ отправлен", schedule: "Расписание", reference: "Ссылка", acknowledgedLabel: "Подтверждено", completed: "Выполнено", collection: "Забор", delivery: "Доставка", temperatureRequired: "Требуется температура", collectionReading: "Температура при заборе (C)", retry: "Повторить", noJobs: "В этом разделе нет заданий.", offline: "Нет соединения. Сохранённые действия будут отправлены после восстановления связи.", sending: "Отправка...", failedRetry: "Не удалось завершить. Повторить", attention: "ВНИМАНИЕ", critical: "КРИТИЧНО", normal: "Обычный", arrived: "ПРИБЫЛ", delayed: "ЗАДЕРЖИВАЮСЬ", problem: "ПРОБЛЕМА", callMe: "ПОЗВОНИТЕ МНЕ", collected: "Забрано", delivered: "Доставлено", driverProfileRequired: "Требуется профиль водителя", unableToLoadJobs: "Не удалось загрузить задания.", unableToLoadInstructions: "Не удалось загрузить инструкции.", unableToAcknowledge: "Не удалось подтвердить инструкцию.", unableToSendResponse: "Не удалось отправить ответ.", temperatureReadingRequired: "Перед отметкой о заборе требуется показание температуры.", temperatureValidNumber: "Температура должна быть допустимым числом.", };

const translations: Record<DriverMobileLanguage, TranslationTable> = { en: english, pt: portuguese, lv: latvian, ru: russian };

export const isDriverMobileLanguage = (value: string | null | undefined): value is DriverMobileLanguage => value === "en" || value === "pt" || value === "lv" || value === "ru";
export const getDriverMobileLanguageKey = (driverId: string) => `${DRIVER_MOBILE_LANGUAGE_KEY_PREFIX}${driverId}`;
export const readDriverMobileLanguage = (driverId: string) => {
  if (typeof window === "undefined") return "en" as DriverMobileLanguage;
  const value = window.localStorage.getItem(getDriverMobileLanguageKey(driverId));
  return isDriverMobileLanguage(value) ? value : "en";
};
export const writeDriverMobileLanguage = (driverId: string, language: DriverMobileLanguage) => {
  if (typeof window !== "undefined") window.localStorage.setItem(getDriverMobileLanguageKey(driverId), language);
};
export const translateDriverMobile = (language: DriverMobileLanguage, key: DriverMobileTranslationKey) => translations[language]?.[key] ?? english[key] ?? "";
export type { DriverMobileTranslationKey };
